#Uma coisa que quero deixar claro para quem visualizar o código é que,
#a palavra "online" é fortemente relacionada a "servidor online mode", ou seja,
#servidores de minecraft original. Não confunda com "jogador online".
#O código não está documentado, então por favor, não faça algo que não sabe, contate-me antes.
#O identificador das punições dos servidores online-mode é UUID, já os piratas, nickname.
#Críticas são fortemente aceitas e analisadas por mim, qualquer bug ou sugestão contate-me.
#Código livre! Caso queira consultar a source peça-me no privado do Discord.
Commands-locked-when-silenced:
  - "/g"
  - "/l"
  - "/anunciar"
  - "/tell"
Warns:
  tree:
    warns: 3
    command: "tempban {jogador} 3:dias Recebeu 3 pontos negativos."
Reasons: #Esses serão os motivos pré-definidos para utilizar no /punir
  reason1:
    reason: "Ofensa a jogador"
    permission: 'punir.ajudante'
    type: TEMPMUTE
    ip: false
    duration: "7:dias,2:meses"
  reason2:
    reason: "Uso de hack"
    permission: 'punir.moderador'
    type: TEMPBAN
    ip: false
    duration: "7:dias,2:meses"
  reason3:
    reason: "Divulgação Grave"
    permission: "punir.moderador"
    type: BAN
    ip: false
    duration: "7:dias,2:meses"