Commands-locked-when-silenced:
  - "/g"
  - "/l"
  - "/anunciar"
  - "/tell"
Warns:
  tree:
    warns: 3
    command: "tempban {jogador} 3:dias Recebeu 3 pontos negativos."
Reasons: #Esses serão os motivos pré-definidos para utilizar no /punir
  reason1:
    reason: "Ofensa a jogador"
    permission: 'punir.ajudante'
    type: TEMPMUTE
    ip: false
    duration: "7:dias,2:meses"
  reason2:
    reason: "Uso de hack"
    permission: 'punir.moderador'
    type: TEMPBAN
    ip: false
    duration: "7:dias,2:meses"
  reason3:
    reason: "Divulgação Grave"
    permission: "punir.moderador"
    type: BAN
    ip: false
    duration: "7:dias,2:meses"