MySQL:
  User: root
  Password: '123'
  Host: 'localhost'
  Port: '3306'
  Database: 'arcanth_db'
Commands-locked-when-silenced:
  - "/g"
  - "/l"
  - "/anunciar"
  - "/tell"
Reasons: #Esses serão os motivos pré-definidos para utilizar no /punir
  reason1:
    reason: "Ofensa a jogador"
    permission: 'punir.ajudante'
    type: TEMPMUTE
    ip: false
    duration: "7:dias,2:meses"
  reason2:
    reason: "Uso de hack"
    permission: 'punir.moderador'
    type: TEMPBAN
    ip: false
    duration: "7:dias,2:meses"
  reason3:
    reason: "Divulgação Grave"
    permission: "punir.moderador"
    type: BAN
    ip: false